### PR TITLE
Add per-window theme example: private browsing theme

### PR DESCRIPTION
**Pull request by nt1m**
Hi! I'm writing a blog post about the theming API, and it should be out this Wednesday. This example is part of it :)

@andymckay @wbamberg

### CODE REVIEW

**Comment by caitmuenster** [comment]
@nt1m Nice! Could you send me a link when you publish the post? Happy to signal boost.

**Comment by nt1m** [comment]
@wbamberg Added the README.md. As for strict_min_version, since Firefox 57 is out soon, I don't think this is too important.

**Comment by nt1m** [comment]
@caitmuenster Thanks! The blog post will be on Mozilla Hacks, I will let you know once it's out!

**Comment by andymckay** [comment]
Oh this is neat, thanks @nt1m. 

Adding in the strict_min_version saves sadness for people on ESR and other browsers from getting upset when it doesn't work pre 57. It's a repository of examples so it's a nice thing to do.

**Comment by nt1m** [comment]
@andymckay @wbamberg Updated.

**Pull request merged**
