### PR TITLE
test travis

### PR DESCRIPTION
**Pull request by andymckay**
do not merge, this is to test that travis ci is set up for pull requests and enforces the code that @yfdyh000 set up

### CODE REVIEW

**Comment by andymckay** [comment]
@wbamberg I'm not an admin on this repo, I think you will need to set up travis ci so it runs.

**Comment by wbamberg** [comment]
@andymckay , can you check if it's running now?

**Comment by andymckay** [comment]
Hmm, doesn't seem to be.

**Comment by andymckay** [comment]
Spoke to soon, totally worked.

We should try and clean up those warnings at some point.

Thanks @wbamberg and @yfdyh000

**Comment by wbamberg** [comment]
Yes, thanks @yfdyh000 !

**Pull request closed without merging**
