### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
grammatical errors are checked and corrected

### Description

updated some grammatical mistakes 
### Motivation

yes

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@madnificent please review my PR

**Comment by 05hiteshbansal** [comment]
@rpl please review my PR

**Comment by 05hiteshbansal** [comment]
@sneakypete81 please review my PR

**Review by Rob--W — CHANGES_REQUESTED** [review]
This doesn't improve the message, and therefore I am closing the issue.

**Pull request closed without merging**
