### PR TITLE
Adds an example for devtools inspector sidebar

### PR DESCRIPTION
**Pull request by nchevobbe**
This adds a webextension example to add an inspector sidebar showing the data of the current selected node in the markup view

### CODE REVIEW

**Comment by andreicristianpetcu** [comment]
This is awesome! I had no clue this API existed! Thank you, @nchevobbe

**Comment by wingman-jr-addon** [comment]
@nchevobbe This PR looks pretty neat! @caitmuenster Do you know has anyone had a chance to evaluate this PR yet?

**Review by rpl — APPROVED** [review]
Looks great.

I'm not sure if the example.json file is still being used to generate the list of examples at:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Examples

If it is it may be nice if we could also add this example in that example.json file, as the other devtools example here:
- https://github.com/mdn/webextensions-examples/blob/60ce50b10ee66f6d706b0715909e756e4bdba63d/examples.json#L142-L153

@chrisdavidmills do you know if we do still regenerate that MDN page from the example.json file in this repo? (and/or how to make sure that the table in the example page is regenerated).

Anyway, we can take care of that in a follow up, and so in the meantime I'm approving this PR as is.

**Comment by caitmuenster** [comment]
@rpl, I just chatted with @chrisdavidmills and it looks like we'll need to manually update the [examples page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) on MDN. Let's go ahead and merge this.

**Comment by rpl** [comment]
> @rpl, I just chatted with @chrisdavidmills and it looks like we'll need to manually update the [examples page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) on MDN. Let's go ahead and merge this.

sure, that sounds absolutely ok to me (also, thanks for double-checking that!)

**Comment by nchevobbe** [comment]
Thanks for meeting this folks!

Le jeu. 12 nov. 2020 à 19:45, Luca Greco <notifications@github.com> a
écrit :

**Pull request merged**
