### PR TITLE
Added "Norwegian Bokmål" lanugage

### PR DESCRIPTION
**Pull request by Wollern**
Added language support for Norwegian Bokmål. (the most common Norwegian
language)

### CODE REVIEW

**Comment by wbamberg** [comment]
@Wollern , thanks!

I tested this out, and it looks as if Firefox expects this language to be called "nb-NO", so the _locales subdirectory would need to be called "nb_NO" (note the underscore, for Chrome compatibility) or "nb".

I tested this by:
* installing the Firefox language pack for Norwegian (https://addons.mozilla.org/en-US/firefox/language-tools/)
* installing the Locale Switcher add-on (https://addons.mozilla.org/en-US/firefox/addon/locale-switcher/)
* switching Firefox into Norwegian
* loading the "notify-link-clicks-i18n" add-on

I found that "nob" didn't work (the language came up as English) but "nb_NO" and just "nb" both did.

You probably know this better than me though. If this seems right to you, could you update the name of the _locales subdirectory, and I'll then merge this?

**Comment by Wollern** [comment]
>
> Hi there,


I’m super new to GitHub, but I think I managed to change it up?
If not, give me a heads up.

Thanks.

**Comment by wbamberg** [comment]
Hi Wollern

The change worked to update the pull request, but you changed it to "no" which does not seem to work in Firefox. You need to change it to "nb" or "nb_NO".

(I'm happy to merge your change as it is, and fix up the name myself, if you don't want to give it another go. Just let me know.)

Will

**Comment by Wollern** [comment]
Wow, I suck.
Maybe I got it right this time..



Med vennlig hilsen // Best regards,
*Jonas Wold-Hansen*
Wold-Hansen WEB
(+47) 46 42 42 48 <+4746424248>

2016-05-31 8:12 GMT+02:00 wbamberg <notifications@github.com>:

**Comment by wbamberg** [comment]
Thanks @Wollern ! And I learned something about the Norwegian language, too :).

**Pull request merged**
