### PR TITLE
Change chrome APIs to browser.

### PR DESCRIPTION
**Pull request by jonathanKingston**
See the same change here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_second_WebExtension$revision/1026038

Thanks

### CODE REVIEW

**Comment by johannhof** [comment]
This means we could also use the new Promise API, would probably make for much nicer code!

**Comment by jonathanKingston** [comment]
@johannhof I can't find docs for that unless you have some. I have seen some mention of the downloads API having promises.

**Comment by andymckay** [comment]
Is there an advantage to this? I can only see the disadvantage that all the APIs won't work across browsers?

**Comment by johannhof** [comment]
@jonathanKingston actually all `browser` APIs should now support returning Promises (if they're async) :)

Anyway, I agree with @andymckay that unless there is some great advantage to this it wouldn't be practical to get rid of the cross-browser compatibility.

So far the only Firefox-exclusive feature that comes with `browser.*` is Promises support, afaik. And I'm not sure if that's worth the switch.

**Comment by andymckay** [comment]
Is anything documenting the difference, for example on this page? https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

Its also worth nothing that all the MDN docs use chrome.* so they at the very least would be incompatible with this change.

**Comment by jonathanKingston** [comment]
@andymckay all the API docs are using browser (this is what sparked me to make the change) for example:
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/move

@johannhof Yup I haven't seen any of the mention of promise support until I read the download api after you mentioned it.

The main advantage would be consistency and explaining they are separate. If however cross compatibility is more important there is probably a decent way to explain the APIs are available under both `chrome` and `browser` global objects.

There probably would be some worth in making a simple shim to make cross compatibility work instead perhaps?

**Comment by andymckay** [comment]
@jonathanKingston how did I miss that... sorry, you are right.

**Comment by andymckay** [comment]
All the docs have now changed to using `chrome`.

**Comment by kumar303** [comment]
I think cross-compatibility is indeed a goal. Anyway, it sounds like this was mostly a documentation problem that has been fixed. Is it ok to close this?

**Comment by wbamberg** [comment]
Yes, I'm happy to close this. I think the chrome/browser question is still not finally resolved, but any resolution probably won't happen in this PR.

**Pull request closed without merging**
