### PR TITLE
Sign CI for extensions.

### PR DESCRIPTION
**Pull request by uiolee**
### Description

Hi there.
I wrote a script for signing extensions. It depends on Github Action. And requires AMO account API

### Motivation

Provides an easier way to install the examples.

#### Procedure

1. Detect whether the manifest changes every time you commit.
1. try to Sign by `sign-addon`.
1. publish to Github Release.

#### How to test

1. `fork` and `clone` this branch
2. set secrets.
    - `WEB_EXT_API_KEY`
    - `WEB_EXT_API_SECRET`
    get api key from https://addons.mozilla.org/zh-CN/developers/addon/api/key/
3. change extensions version.
4. push to `main` or `sign` branch

##### Whether the ID should be saved to the repository

if not:

  - It takes longer to wait for each signing. 
  - You will see multiple duplicates of the same extension in your AMO account. 
  - version can be the same.

### Related issues and pull requests

#397

### CODE REVIEW

**Comment by Rob--W** [comment]
The Github actions in this repo are meant to support the maintenance of extension examples. The proposed signing action does not fit in this repository.

**Comment by uiolee** [comment]
Then maybe we should remove those built version in `/build`

**Comment by Rob--W** [comment]
> Then maybe we should remove those built version in `/build`

We probably should. We should check whether anything references it and if not just delete it.

**Comment by rebloor** [comment]
See  Remove built extensions #397.

**Pull request closed without merging**
