### PR TITLE
Added an example of the search API

### PR DESCRIPTION
**Pull request by wbamberg**
This PR adds a new example WebExtension that demonstrates the [search API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search).

The example retrieves the list of installed search engines, and adds a context menu item for each one, displayed in the "selection" context.

Each context menu item searches for the selected text using the corresponding search engine.

This enables a user to:
* select some text to search for
* activate the context menu
* choose which search engine to use for the search.

### CODE REVIEW

**Comment by wbamberg** [comment]
@mkaply, would you mind taking a look at this example, please?

**Comment by mkaply** [comment]
Overall looks good. A couple things.

1. Remove the sidebar stuff from manifest.json.
2. You'll need to remove the default_locale line if there is no locale information.

Search stuff looks great.

**Comment by KanhaiyaAryal** [comment]
This is great and it's help me to develop.

**Comment by wbamberg** [comment]
Thanks @mkaply . Yes, it seems like I included totally the wrong manifest.json in this PR. I've also updated strict_min_version to match the version that this API appeared in.

**Pull request merged**
