### PR TITLE
history-deleter: Move the comment about limiting items to the place it belongs

### PR DESCRIPTION
**Pull request by bobsilverberg**
I found this issue when reviewing the docs for history. I think this comment makes more sense where I have moved it.

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks Bob! I saw this too, but forgot to change it :(.

**Comment by Cobe1** [comment]
why is all this in account and personal email

**Comment by Cobe1** [comment]
also business email. Can these notes and merginings commits into my account be explained

**Comment by wbamberg** [comment]
@Cobe1 , you are watching this repository, which means (depending on your [notification settings](https://github.com/settings/notifications)) that you will receive emails when people comment on PRs and issues. If you don't want this, stop watching the repo or change your notification settings.

**Pull request merged**
