### PR TITLE
fixes mdn#12813 icon sizes

### PR DESCRIPTION
**Pull request by himanshugarg**
1. Fixes https://github.com/mdn/content/issues/12813 Scales icon sizes to match description in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension . 
2. Their license terms do not talk about modification, but I hope they permit scaling (alongwith backlinking).
3. Thanks [ssxxaazz](https://github.com/ssxxaazz) for reporting

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Review by Rob--W — CHANGES_REQUESTED** [review]
The modified icons are blurry. Is there a source image in vector format from which new images can be generated, to avoid the loss of quality by resizing the png version?

**Comment by himanshugarg** [comment]
> The modified icons are blurry. Is there a source image in vector format from which new images can be generated, to avoid the loss of quality by resizing the png version?

Thanks for the review. Only the scaled up icons (beasts-32) look blurred or the scaled-down ones (beasts-48) also? If just the former I can create from a larger png as the svg equivalents are not free. If both, we might have to look at other sources. Thanks

**Comment by himanshugarg** [comment]
In Light Theme:
image

In Dark Theme:
image

[Turtle](https://icons8.com/icon/9187/turtle) icon by [Icons8](https://icons8.com)

**Comment by Rob--W** [comment]
The icons have completely changed, which makes it inconsistent with what's actually documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension.

Is it possible to not change the appearance?

**Comment by himanshugarg** [comment]
> The icons have completely changed, which makes it inconsistent with what's actually documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_second_WebExtension.

Sorry about this. I have now resized only the BG for small icons by 1px on each side and scaled down the large one using `nohalo` compression.

**Review by Rob--W — APPROVED** [review]
LGTM, thanks!

**Comment by achangofpace** [comment]
Did this not get merged? The issue (https://github.com/mdn/webextensions-examples/issues/544) is still open pending this PR.

**Pull request closed without merging**
